app_name = "toy synth"

[synthesis]
sample_rate = 44100
sample_buffer_target_size = 4096
frames_per_buffer = 64

[mqtt]
host = "localhost"
port = 1883

[[mqtt.topics]]
name = "log"
path = "toy/log"

[[mqtt.topics]]
name = "command test"
path = "toy/synth/test/command"